// ADD PARAMETERS
export const ADD_PARAMETERS = 'ADD_PARAMETERS';
//Fetch Parameters
export const FETCH_PARAMETERS = 'FETCH_PARAMETERS';

// ADD USER INFORMATION

export const ADD_USER_INFORMATION = 'ADD_USER_INFORMATION';

// ADD CREDIT
export const ADD_CREDIT = 'ADD_CREDIT';

// SEND DATA
export const SEND_DATA = 'SEND_DATA';
export const SEND_DATA_SUCCESS = 'SEND_DATA_SUCCESS';
export const SEND_DATA_FAILURE = 'SEND_DATA_FAILURE';


